server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/apidemo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull&allowPublicKeyRetrieval=true
    username: sbsst
    password: sbs123414
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
#      ddl-auto: create
#      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDB53Dialect

# 전체 로그 레벨 설정(기본 info)
logging.level.root: info

# hello.springmvc 패키지와 그 하위 로그 레벨 설정
logging.level.sbs.apidemo: debug


